/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sestavineseminar;

import java.util.*;
import javax.swing.DefaultListModel;


/**
 *
 * @author marti
 */
public class Sestavinar2000 extends javax.swing.JFrame {

    sestavinaDao implSes = new sestavinaDaoImpl();
    receptDao implRec = new receptDaoImpl();
    DefaultListModel seznamSestavinM = new DefaultListModel();
    DefaultListModel seznamObrokovM = new DefaultListModel();
    DefaultListModel dodajSestavine = new DefaultListModel();
    DefaultListModel seznamSestavinRecepta = new DefaultListModel();
    ArrayList<sestavina> sestavine = new ArrayList();
    ArrayList<recept> recepti = new ArrayList();

    public void napolniSeznamSestavin(DefaultListModel model) {
        model.clear();
        sestavine = implSes.getAllsestavine();
        for (sestavina ses : sestavine) {

            model.addElement(ses.getId() + "," + ses.getNaziv());
        }
    }

    public void napolniSeznamReceptov(DefaultListModel modelReceptov, ArrayList<recept> recepti) {
        modelReceptov.clear();
        for (recept rec : recepti) {
            modelReceptov.addElement(rec.getId() + ", Naziv: " + rec.getNaziv() + ", Stevilo Sestavin: " + rec.getStSestavin());
        }
    }

    public Sestavinar2000() {
        initComponents();
        sestavine = implSes.getAllsestavine();
        napolniSeznamSestavin(seznamSestavinM);
        napolniSeznamSestavin(dodajSestavine);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSeznamSestavinM = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSeznamObrokovM = new javax.swing.JList<>();
        btnPreveriSestavine = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPridobiVseObroke = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtOpisP = new javax.swing.JTextArea();
        txtID = new javax.swing.JTextField();
        txtImeP = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        listSestavineRecepta = new javax.swing.JList<>();
        jTextField6 = new javax.swing.JTextField();
        txtStSes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDodajSestavine = new javax.swing.JList<>();
        btndodajRecept = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDodajNaziv = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDodajOpis = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDodajStSes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtImeSestavine = new javax.swing.JTextField();
        btnDodajSes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("izberite  sestvaine:");

        listSeznamSestavinM.setModel(seznamSestavinM);
        jScrollPane1.setViewportView(listSeznamSestavinM);

        listSeznamObrokovM.setModel(seznamObrokovM);
        listSeznamObrokovM.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSeznamObrokovMValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listSeznamObrokovM);

        btnPreveriSestavine.setText("izvedi");
        btnPreveriSestavine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreveriSestavineActionPerformed(evt);
            }
        });

        jLabel5.setText("obroki, ki jih lahko narediete:");

        btnPridobiVseObroke.setText("Pridobi vse obroke");
        btnPridobiVseObroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridobiVseObrokeActionPerformed(evt);
            }
        });

        jButton1.setText("zbriši recept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPreveriSestavine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPridobiVseObroke)
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)))
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPridobiVseObroke)
                            .addComponent(jButton1)))
                    .addComponent(btnPreveriSestavine)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main", jPanel1);

        jLabel6.setText("ID:");

        jLabel7.setText("Ime recepta:");

        jLabel8.setText("opis:");

        jLabel9.setText("st sestavin");

        txtOpisP.setColumns(20);
        txtOpisP.setRows(5);
        jScrollPane5.setViewportView(txtOpisP);

        listSestavineRecepta.setModel(seznamSestavinRecepta);
        jScrollPane6.setViewportView(listSestavineRecepta);

        jTextField6.setText("jTextField6");

        jLabel12.setText("sestavne recepta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtImeP))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStSes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtImeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(80, 80, 80)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStSes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Podrobnosti", jPanel2);

        listDodajSestavine.setModel(dodajSestavine);
        jScrollPane3.setViewportView(listDodajSestavine);

        btndodajRecept.setText("dodaj recept");
        btndodajRecept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndodajReceptActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime recepta:");

        jLabel3.setText("Opis:");

        txtDodajOpis.setColumns(20);
        txtDodajOpis.setRows(5);
        jScrollPane4.setViewportView(txtDodajOpis);

        jLabel4.setText("izberite  sestavine:");

        jLabel10.setText("Število sestavin:");

        jLabel11.setText("Ime sestavine:");

        btnDodajSes.setText("dodaj sestavino");
        btnDodajSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajSesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndodajRecept)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDodajNaziv))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDodajStSes)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtImeSestavine, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnDodajSes))))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDodajNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtDodajStSes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtImeSestavine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(btnDodajSes)
                                .addGap(157, 157, 157)))
                        .addComponent(btndodajRecept))
                    .addComponent(jScrollPane3))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dodaj recept/sestavino", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndodajReceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndodajReceptActionPerformed
        recept rec = new recept();
        String naziv, nazivSes, opis;
        int stSestavin, id;
        ArrayList<sestavina> sestavin = new ArrayList();
        naziv = txtDodajNaziv.getText();
        opis = txtDodajOpis.getText();
        stSestavin = Integer.parseInt(txtDodajStSes.getText());
        for (String a : listDodajSestavine.getSelectedValuesList()) {
            sestavina sestavina1 = new sestavina();
            id = Integer.parseInt(a.substring(0, a.indexOf(",")));
            nazivSes = a.substring(a.indexOf(",") + 1);
            sestavina1.setId(id);
            sestavina1.setNaziv(nazivSes);
            sestavin.add(sestavina1);

        }
        rec.setNaziv(naziv);
        rec.setOpis(opis);
        rec.setStSestavin(stSestavin);

        implRec.insertRecept(rec, sestavin);

        recepti = implRec.getAllRecept();
        napolniSeznamReceptov(seznamObrokovM, recepti);
    }//GEN-LAST:event_btndodajReceptActionPerformed

    private void btnPreveriSestavineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreveriSestavineActionPerformed
        if (!listSeznamSestavinM.getSelectedValuesList().isEmpty()) {
            int id;
            String naziv;

            ArrayList<sestavina> sestavin = new ArrayList();
            for (String a : listSeznamSestavinM.getSelectedValuesList()) {
                sestavina sestavina1 = new sestavina();
                id = Integer.parseInt(a.substring(0, a.indexOf(",")));
                naziv = a.substring(a.indexOf(",") + 1);
                sestavina1.setId(id);
                sestavina1.setNaziv(naziv);
                sestavin.add(sestavina1);

            }
            recepti = implRec.getreceptBasedOnGiven(sestavin);
            napolniSeznamReceptov(seznamObrokovM, recepti);
        }
    }//GEN-LAST:event_btnPreveriSestavineActionPerformed

    private void btnDodajSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajSesActionPerformed
        String naziv;
        naziv = txtImeSestavine.getText();
        sestavina s = new sestavina();
        s.setNaziv(naziv);
        implSes.insertSestavina(s);
        napolniSeznamSestavin(seznamSestavinM);
        napolniSeznamSestavin(dodajSestavine);
    }//GEN-LAST:event_btnDodajSesActionPerformed

    private void btnPridobiVseObrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridobiVseObrokeActionPerformed
        recepti = implRec.getAllRecept();
        napolniSeznamReceptov(seznamObrokovM, recepti);
    }//GEN-LAST:event_btnPridobiVseObrokeActionPerformed

    private void listSeznamObrokovMValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSeznamObrokovMValueChanged
        String izbira = listSeznamObrokovM.getSelectedValue();
        if (izbira != null) {

            ArrayList<String> seznamSestavin = new ArrayList();
            recept rec = new recept();
            int id = id = Integer.parseInt(izbira.substring(0, izbira.indexOf(",")));
            rec = implRec.getReceptByID(id);
            txtID.setText(String.valueOf(rec.getId()));
            txtImeP.setText(rec.getNaziv());
            txtOpisP.setText(rec.getOpis());
            txtStSes.setText(String.valueOf(rec.getStSestavin()));

            seznamSestavin = implRec.getAllSestavineRecepta(id);
            seznamSestavinRecepta.clear();
            seznamSestavin.forEach((action) -> seznamSestavinRecepta.addElement(action));
        } else {
            txtID.setText("");
            txtImeP.setText("");
            txtOpisP.setText("");
            txtStSes.setText("");
        }
    }//GEN-LAST:event_listSeznamObrokovMValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String izbira = listSeznamObrokovM.getSelectedValue();
        int id = id = Integer.parseInt(izbira.substring(0, izbira.indexOf(",")));

        implRec.deleteRecept(id);
        recepti = implRec.getAllRecept();
        napolniSeznamReceptov(seznamObrokovM, recepti);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sestavinar2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sestavinar2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sestavinar2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sestavinar2000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sestavinar2000().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajSes;
    private javax.swing.JButton btnPreveriSestavine;
    private javax.swing.JButton btnPridobiVseObroke;
    private javax.swing.JButton btndodajRecept;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JList<String> listDodajSestavine;
    private javax.swing.JList<String> listSestavineRecepta;
    private javax.swing.JList<String> listSeznamObrokovM;
    private javax.swing.JList<String> listSeznamSestavinM;
    private javax.swing.JTextField txtDodajNaziv;
    private javax.swing.JTextArea txtDodajOpis;
    private javax.swing.JTextField txtDodajStSes;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtImeP;
    private javax.swing.JTextField txtImeSestavine;
    private javax.swing.JTextArea txtOpisP;
    private javax.swing.JTextField txtStSes;
    // End of variables declaration//GEN-END:variables
}
